version: "3.5"

services:

  data_server:
    build:
      context: data_server
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8080

    environment:
      DJANGO_SETTINGS_MODULE: data_server.settings
    expose:
      - "8080"
    ports:
      - "8080:8080"

  ui:
    depends_on:
      - data_server
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"