# Generated by Django 3.1.6 on 2021-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210207_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(default='[]'),
        ),
    ]
